---
- name: Download the Kafka binaries on the controller node
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /tmp/

- name: Create /opt/kafka directory
  file:
    path: /opt/kafka
    state: directory
    mode: "0755"

- name: Untar the Kafka binaries on the target nodes
  unarchive:
    src: /tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /opt/kafka

- name: Setting up Kafka server properties
  lineinfile:
    path: /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties
    regexp: "^advertised.listeners="
    line: advertised.listeners=PLAINTEXT://{{ ansible_hostname }}:9092

- name: Setting up Kafka server listeners
  lineinfile:
    path: /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties
    regexp: "^zookeeper.connect="
    line: zookeeper.connect={{ ansible_hostname }}:2181

- name: Start Zookeeper server
  shell: /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/bin/zookeeper-server-start.sh /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/config/zookeeper.properties &

- name: Start Kafka server
  shell: /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/bin/kafka-server-start.sh /opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties &