---
- name: Download the Kafka binaries on the controller node
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /tmp/

- name: Untar the Kafka binaries on the target nodes
  unarchive:
    src: /tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /opt/kafka

- name: Setup environment variables
  shell: "PATH=$PATH:"