---
- name: Download the Kafka binaries on the controller node
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /tmp/

- name: Untar the Kafka binaries on the target nodes
  unarchive:
    src: /tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /opt/kafka

- name: Setup environment variables
  shell: "export PATH=$PATH:/opt/kafka/bin"

- name: Setting up Kafka server properties

- name: Setting up Kafka server listeners

- name: Connecting Kafka to Zookeeper

- name: Start Zookeeper server

- name: Start Kafka server